### ISSUE TITLE
Publish this Package

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents-python#13]
## Expected Behavior

This package should be published to PyPi. Check with Yoshi for best practices.

**Comment by grant** [comment]
Chen will talk to the DPE team this week on the release process.

**Comment by michaelawyu** [comment]
Have reached out the library team; Bu Sun will send a PR tomorrow to set up the release templates.

**Comment by michaelawyu** [comment]
The release PR has been merged. The package should be available soon.

**Comment by eclipselu** [comment]
Is the package available in PyPi?

**Comment by Haolicopter** [comment]
It looks like the package is still not available.
```
ERROR: Could not find a version that satisfies the requirement google-events
ERROR: No matching distribution found for google-events
```

**Comment by grant** [comment]
> Is the package available in PyPi?

It's not available right now. @michaelawyu can you provide an update?

Is this the right package?

https://pypi.org/project/google-events/

**Comment by michaelawyu** [comment]
The package is available at https://pypi.org/project/google-events/0.1.1/.
