### ISSUE TITLE
Tests for the Python Unmarshaling Library are Failing

### ISSUE THREAD

**Issue by michaelawyu** [googleapis/google-cloudevents-python#36]
## Expected Behavior

All 6 tests auto-generated for the Python unmarshaling library should pass.

## Actual Behavior

4 of 6 tests are passing; 2 fail due to schema issues.

## Specifics

Per the protobuf event definitions, the `request` field of the `AuditLog` message (`proto/google/events/cloud/audit/v1/data.proto`) should be a `Struct`, which corresponds to free-form k-v pairs (dictionaries) in Python. However, after translation, the converted JSON schema (`jsonschema/google/events/cloud/audit/v1/LogEntryData.json`) has the same field specified as an object with one attribute, `fields`. This representation no longer matches the test data (`testdata/google/events/cloud/audit/v1/LogEntryData-pubsubCreateTopic.json`, which has two k-v pairs, `@type` and `name`), hence the failed tests. 

## Steps to Reproduce the Problem

Run `pytest` at the root of the Python Unmarshaling Library repository.

**Comment by grant** [comment]
Transferring this issue to the python repo. There's not enough detail for me to triage this issue.

**Comment by grant** [comment]
Still an issue.

**Comment by dinagraves** [comment]
Correct - the autogenerated tests are failing:

```
 AttributeError: 'StorageObjectData' object has no attribute 'crc32c'

AttributeError: 'Request' object has no attribute 'name'
```

https://github.com/googleapis/google-cloudevents-python/pull/21

**Comment by dinagraves** [comment]
The first problem was that the sample data was passing in 'crc32c' when it should have been 'crc32C'.  If you look [here](https://github.com/googleapis/google-cloudevents-python/blob/master/src/google/events/cloud/storage/v1/StorageObjectData.py#L140), you'll see  it expressed as `crc32_c`.  Whatever is expressed in snake case in javascript will be expressed as an underscore in Python, so when you change the sample data to a capital `C`, then it maps properly. 

I guess this sample data was auto-generated?  I'll follow up on that but have created a PR to fix the test for now.

**Comment by dinagraves** [comment]
Can confirm the 2nd failing test is as described in the original post above.

**Comment by dinagraves** [comment]
The easy one was fixed: https://github.com/googleapis/google-cloudevents-python/pull/61.  Following up with the Yoshi team to try to understand the behavior of the Struct proto -> python API.

**Comment by dinagraves** [comment]
Talked to Grant -- the library should probably be regenerated and from there we should look at the generation script to understand why it's translating the `Struct` the way it is.

**Comment by engelke** [comment]
@parthea Can you verify whether this is still happening or not?
