### ISSUE TITLE
Refactor the Generator

### ISSUE THREAD

**Issue by grant** [googleapis/google-cloudevents-python#39]
## Expected Behavior

The generator should produce consistent results, ideally automated for producing the build.

We should not be removing folders and creating temporary folders if not needed.

https://github.com/googleapis/google-cloudevents-python/blob/master/gen.sh

## Actual Behavior

Right now we have a script that uses a `workplace` directory. The generator results are inconsistent across machines.

## Steps to Reproduce the Problem

Run the generator:

```
./gen.sh
```

Related issue: https://github.com/googleapis/google-cloudevents-python/issues/30

**Comment by engelke** [comment]
PR #134 addressed this issue. It does create and remove temporary folders automatically, and is suitable for automation.
